import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className="bg-slate-200">
        <header>
          <div className="bg-slate-200">
            <div className="max-w-7xl mx-auto min-h-screen">
              <nav>
                <ul className="flex">
                  <li className="m-2 p-2 bg-indigo-500 text-white rounded-md">
                    <Link href='/home'>Home</Link>
                  </li>
                  <li className="m-2 p-2 bg-indigo-500 text-white rounded-md">
                    <Link href='/pessoas'>Pessoas</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
