services:

  # frontend:
  #   container_name: frontend_crud
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  backend:
    container_name: laravel-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:80
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ''
      DB_DATABASE: backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: backend
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
