version: "3.7"

services:
  frontend:
    container_name: frontend_crud
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"

  backend:
    container_name: backend_crud
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: database_crud
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"